version: '3.9'

services:
  pay:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    networks:
      - cry-network

networks:
  cry-network:
    name: 'cry-network'
    external: true
